In [76]:
# Creating a numpy array

import numpy as np
grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])
grades

array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [77]:
# Calculating Mean
grades

array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [78]:
print(np.mean(grades))

87.5


In [79]:
# Calculating Median
grades

array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [80]:
print(np.median(grades))

88.5


In [81]:
# Calculating Standard Deviation
grades

array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [82]:
print(np.std(grades))

6.591661399070799


In [83]:
# Finding Max and Min of the grades
grades

array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [84]:
print(np.max(grades)) # Maximum of the grades

98


In [85]:
print(np.min(grades)) # Minimum of the grades

75


In [86]:
# Sorting the grades in Ascending order
grades

array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [87]:
grades = np.sort(grades)

In [88]:
grades

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

In [89]:
# Finding the index of the highest grade
grades

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

In [90]:
grades[-1]

98

In [91]:
# Number of Students who scored above 90
grades

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

In [92]:
grades[grades > 90]

array([92, 95, 98])

In [93]:
# Percentage of Students who scored above 90
import numpy as np
grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])
grades

array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [94]:
np.mean(grades > 90) * 100 # Percentage of Students who scored above 90

30.0

In [95]:
# Percentage of Students who scored above 75
np.mean(grades > 75) * 100

90.0

In [96]:
# Extracting all the grades above 90 and put them in a new array called "high_performers".

import numpy as np
grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])
grades

array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [97]:
grades[grades > 90]

array([92, 95, 98])

In [98]:
high_performers = grades[grades > 90]  # Giving the array a new variable

In [99]:
high_performers

array([92, 95, 98])

In [100]:
# Create a new array called "passing_grades" that contains all the grades above 75.

grades[grades > 75]

array([85, 90, 88, 92, 95, 80, 98, 89, 83])

In [101]:
passing_grades = grades[grades > 75]

In [102]:
passing_grades

array([85, 90, 88, 92, 95, 80, 98, 89, 83])